version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - API_PORT=8000
      - API_HOST=0.0.0.0
      - AUTH_API_KEY=${AUTH_API_KEY}
      - TIKTOKEN_TOKENIZER_MODEL=${TIKTOKEN_TOKENIZER_MODEL}
      - ALBERT_API_KEY=${ALBERT_API_KEY}
      - ALBERT_ENDPOINT=${ALBERT_ENDPOINT}
      - ALBERT_VECTORISATION_MODEL=${ALBERT_VECTORISATION_MODEL}
