services:
  postgres:
    image: postgres:14
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: postgrespassword

volumes:
  db_data: