apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: www-secret
spec:
  encryptedData:
    AUTH_API_KEY: AgA+9+7ifif1Z8la8rzL6Rc0hvGpuGqzJv1ZH7A68xZNiu9/cM3lZwbUXWsdOc3WGU/NxxffPan155cf9GbRlu+e4hf32yUJ9ughz/y84TQkAKxR7COWNxOU+2+Ln+gWv2CzKtxGFdfbT33j0UcCO0G3q7xAENO7EmeTS2svAbZa9wm4q2vFkIBwJUD5oqGTCWiBTaHKM5pzHMGCAMCluHI9MxHQgpaNRYGtrvYE35Q4oVNDkkZWZR1lxVogEfxETNZLIDqujMwsi7JRcqJmveTLme1OwSyHt+4d4xP2prAH/GxM+ZbJfGx5fqvBOf6S4jlTUoh1Yk3LwsJIFDzzQQr8FduvGxURue6WKn3KorWXXFB2PPqzqeTgpD68hZA7y/KKErvFikZqZC6JC0jgjBj9d+SeZe66enM3+YR7HeSDJV/2JdPC5uhR3j9AM9TJqfhcv6EaAdyR76y9x7WPlaCpnNnq8ysa1pX9S3uVvolfrEelZfguIc8vmkD923WHzLSD7W4NWgJMo9w4SFU+fJFJY4gAWwM1Yiwkar1GsBgPUOjMc1oYDAVa6gK6Ql/kkKOBzAklFtjPdtNmdLVWF2w48gLA1ZvlhssyY5BYX9jBD8/Oz0Y6ftS9ePWe/z/mBKX9ITXuVd/qivVkWbaOxum3X9JRaW8ByfXqtuUL1kkUXJUph8YDTFhbz7Ps+5i2Fx533MK4jSIrG4fvku+28NJzQqiK6zahklIA+4QIEIfg+G56/REbAMR7y8ncPA==
    ALBERT_API_KEY: AgBIagvDu20vIgS75DeDAKyXGFKrtdkUgcFX88w8fO1b4a+JNblGGAxnCc/OcWukDug5D+GjPy9IXdGXNCoPeOumfH1FYBDRjJqrN5qiVjM04ltZw0vXIRXb0KDXSq8JVTgbx6ABu64tZwFtfUiKThwDUtEynLvmnFImo1bLPplRZTg2RZppkXvVAsLRkHXN8iuNGaBfWGiANx7iBZ3NESQaJOFLA998GgnpE3Ye8gU0yxEsCQARKPc1xqsu28QNqrOB62gm1k0lRC6NIKcn1Buy7NTmTTPna5b7sKjrafA2TfZu0rHzcEpvy8SoTSbHg52xIrZHUKDzIvVEnuEfkIvDfIXsama4jLmg7RzQaJumoVC3kuHoG/aaQWBN6ywtjD7oTH400h/tBVeTjbGybb/jIwjGzeJd4gN6lesQNVPi+/h46GN39MZoG3NlqErGoyD0YVRKl8l8zlDGpwni/QddLry6YvPTxgCcwJy2rk1ZOtLI+HmA3UeJLRZIqALy6JT/03q2pvffJUaz/1aquXR9ud+LbdZgk3GSbCD6pPHYEY7MOupx7XfdcOVI0rkQkNvS38yYfDUgAOKdS8NQuA/X7qDYk+UDi/hmN6g0j34we9l/ASHc6Qwm8U147WYu0igeeBiggYfeGDm0nfuLG2XnV8eSM+xLswpENvlvOaBbMD61CaTkD7+xByml/jlVxtoQwxX8VJ20Ug2Af1LIzAFsOefnBhqURREBSAMuo/S4R5EBoGf4OLnamOWKmJTtqk23rDrWBHh8gXD/Vd0dtXq1k5RtVN4lcMcgUuI=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: www-secret
    type: Opaque
