name: Code quality

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  cancel-in-progress: true
  group: quality-${{ github.ref }}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Install dependencies
        run: poetry install
        working-directory: ./api

      - name: Lint
        run: poetry run ruff check
        working-directory: ./api

  format:
    name: Code formatter checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
        working-directory: ./api

      - name: Install dependencies
        run: poetry install
        working-directory: ./api

      - name: Code formatter checker
        run: poetry run ruff format --check

  type-check:
    name: Check types
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
        working-directory: ./api

      - name: Install dependencies
        run: poetry install
        working-directory: ./api

      - name: Type-check
        run: poetry run pyright
        working-directory: ./api

  hook:
    name: Precommit hook
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
        working-directory: ./api

      - name: Install dependencies
        run: poetry install
        working-directory: ./api

      - name: Pre-commit
        run: poetry run pre-commit run --all-files
        working-directory: ./api

  docker:
    name: Lint Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          recursive: true
