name: 👓 Review Auto
on:
  push:
    branches:
      - "**"
      - "!renovate/**"
      - "!dependabot/**"
      - "!dev"
      - "!main"

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.ref }}

jobs:
  socialgouv:
    name: "🇫🇷 SocialGouv"
    uses: socialgouv/workflows/.github/workflows/use-ks-gh-with-env-review-auto.yaml@v1
    secrets: inherit
